"""remove watch history

Revision ID: 52080c49d898
Revises: 0dad2f3e21bd
Create Date: 2025-12-24 12:47:36.928626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52080c49d898'
down_revision: Union[str, Sequence[str], None] = '0dad2f3e21bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watch_histories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watch_histories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('watched_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], name=op.f('watch_histories_content_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('watch_histories_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('watch_histories_pkey'))
    )
    # ### end Alembic commands ###
